### ISSUE TITLE
Asks users to activate TLC execution statistics

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#114]
The Toolbox nudges users to activate execution statistics to guide TLC development (see screenshot below).  Please add similar functionality to the vscode TLA+ editor.  Technically, a file called esc.txt is dropped into ```~/.tlaplus/``` whose first line is either a random identifier, "RANDOM_IDENTIFIER", or "NO_STATISTICS" (see https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/util/ExecutionStatisticsCollector.java).

![Screenshot from 2019-10-21 13-18-55](https://user-images.githubusercontent.com/88777/67240009-618aa200-f405-11e9-840e-05e165b92dd0.png)

The statistics are publicly available: https://exec-stats.tlapl.us/tlaplus.csv

**Comment by alygin** [comment]
Sure.

**Comment by lemmy** [comment]
The "toolbox" field has been modeled as a boolean but maybe should change to indicate the actual IDE.

**Comment by alygin** [comment]
@lemmy, the implementation is in the [v1.3 pre-release](https://github.com/alygin/vscode-tlaplus/releases).

As for the TLC `-tool` option, I agree that it would be nice to distinguish various TLA+ IDE's by providing different values. But wouldn't a string value (like "toolbox", "vscode-tlaplus", or some kind of mnemonic, like "TB" or "VSC") be more convenient?

**Comment by lemmy** [comment]
Would it be difficult for the extension to set a Java system property (e.g. ```-Dtlc2.TLC.tool=vscode```)?

**Comment by alygin** [comment]
Not difficult at all.
Does TLC already handle this property?

**Comment by lemmy** [comment]
No, but I have to think how to best migrate the current reporting.

**Comment by lemmy** [comment]
Actually, I like "tlc2.TLC.ide" better.

**Comment by lemmy** [comment]
Added with https://github.com/tlaplus/tlaplus/commit/fe636624af94a06f943d6d4cd759803b3cea90eb.  I suggest you include the  [TLC nightly build](https://nightly.tlapl.us/dist/) in the final 1.3.0 extension release?

Metabase:
![Screenshot from 2019-11-30 16-08-32](https://user-images.githubusercontent.com/88777/69907544-b964e300-138b-11ea-97e7-4efb48f30c59.png)

**Comment by alygin** [comment]
> I suggest you include the TLC nightly build in the final 1.3.0 extension release?

Is it stable enough?

**Comment by lemmy** [comment]
Yes, TLC development is very conservative.

**Comment by alygin** [comment]
Added to the latest [v1.3 pre-release](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.3.0-alpha.3).

**Comment by lemmy** [comment]
There is a typo "plublicly" in the settings label: ```Allows you to send the TLC usage statistics to the plublicly available database. You can find more details on what is shared here.```

Do you want me to create an exec-stats.md file in the https://github.com/tlaplus/tlaplus repo that lists the shared information?

**Comment by lemmy** [comment]
Should the drop-down in the settings show if a user has opted-in or not?? Here it shows "doNotShare" even though I have a ~/.tlaplus/esc.txt file with an identifier.

**Comment by alygin** [comment]
> There is a typo

Thanks, fixed.

> Do you want me to create an exec-stats.md?

Yeah, I think it would be more appropriate to have a page like [this](https://github.com/alygin/vscode-tlaplus/wiki/TLC-Statistics-Sharing) in the tlaplus/tlaplus repo, since it is the source of truth for such information. I'll change the link as soon as such page is available.

> Should the drop-down in the settings show if a user has opted-in or not?

Actually, I thought I couldn't update configuration settings programmatically, but it looks like there's a method for that, so yes, I'll do that.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/util/ExecutionStatisticsCollector.md

**Comment by alygin** [comment]
All fixes are available in the latest [pre-release](https://github.com/alygin/vscode-tlaplus/releases).

**Comment by alygin** [comment]
@lemmy, I think I'll stick to the stable tla2tools.jar bundled with the extension. Using nightlies will be possible after implementing #134.

**Comment by alygin** [comment]
Just released v1.3 with statistics sharing, so I'm closing the issue. Please, feel free to reopen it if sharing doesn't work as expected.

I'll put the `-Dtlc2.TLC.ide=vscode` option back when tla2tools 2.15 is released.

**Comment by lemmy** [comment]
There is no harm in passing ```-Dtlc2.TLC.ide=vscode``` to older TLC releases because it is ignored.

**Comment by alygin** [comment]
Yeah, I noticed that, but still decided to remove the option because some people look at the full TLC command line and they may be confused by this previously unknown option that actually does nothing at the moment.

**Comment by lemmy** [comment]
The link to the file explaining the content of the stats has changed to: https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/util/ExecutionStatisticsCollector.md
