### ISSUE TITLE
Cannot run TLC a second time

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#115]
TLC correctly terminated. Have to restart vscode.

```
markus@avocado:~$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
markus@avocado:~$ uname -a
Linux avocado 4.18.0-16-generic #17~18.04.1-Ubuntu SMP Tue Feb 12 13:35:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

![Peek 2019-11-06 15-58](https://user-images.githubusercontent.com/88777/68348418-ab82b180-00ae-11ea-8b9f-68289695a5ec.gif)

Notice that "TLA+: Check model" is no longer available in the command palette when it's opened the second time.

**Comment by alygin** [comment]
There's no need to restart VS Code, you just need to switch the focus back to the .tla or .cfg file. The "Check model" command is only available when the active editor is a .tla/.cfg file, so the extension would know what model to check. When the TLC visualization panel is open, VSCode switches focus to it and the check command becomes disabled.

I see two things to be done to not confuse the user here:
- Check if it's possible to use the [onWebviewPanel activation point](https://code.visualstudio.com/api/references/activation-events#onWebviewPanel) to enable the check command when the visualization panel is active.
- Describe how the check process works in the wikis.

**Comment by lemmy** [comment]
The fact that "Stop" keeps visible even if TLC has terminated correctly is confusing too.

**Comment by alygin** [comment]
You're right, this can be improved too.

The reason it works this way is that the rules to enable/disable commands are declarative and rely on [the set of contexts](https://code.visualstudio.com/docs/getstarted/keybindings#_contexts) predefined in the VS Code platform. The TLC running status is not one of such contexts, so making the command availability depend on it is a bit tricky. I believe it can be done somehow, but haven't worked on it yet.

**Comment by alygin** [comment]
> The fact that "Stop" remains visible even if TLC has terminated correctly is confusing too.

I think it deserves a separate issue: #116

**Comment by lemmy** [comment]
https://twitter.com/DrQz/status/1216886565818863617

**Comment by alygin** [comment]
@lemmy, a couple of enhancements is available in the pre-release. One can now easily repeat the last TLC run with a special command or a button on the check visualization panel.
Running TLC from the Explorer context menu is now also supported.

**Comment by lemmy** [comment]
Nice!

I suggest to rename the context menu to "Check Model with TLC" or "Check TLA+ model" to prevent clashes with other extensions.  It is also not obvious if "Repeat" checks a snapshot of the old model (ignoring any modifications after model checking) or if it picks up modifications.

**Comment by lemmy** [comment]
It would also be useful to know which model/config I'm going to repeat (assuming there is more than one).

**Comment by alygin** [comment]
I agree. Will back to it soon.

**Comment by alygin** [comment]
Several fixes and improvements are available in the new pre-release.

**Comment by alygin** [comment]
Since v1.5 there's a command to run the last TLC check again, a link on the visualization panel to do the same, and a field on the panel that displays the spec and model file names.
