### ISSUE TITLE
Open existing Spec.out file in "TLA+ model checking" panel

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#118]
Please add support to open an existing Spec.out file from a previous TLC run in the "TLA+ model checking" panel.

Background: Toying with VSCode Online where two users collaborate on a single spec. One runs TLC the other one wants to look at the error trace in the the shared Spec.out file.  Collaboration works at the spec level but the  "TLA+ model checking" panel is unfortunately not a first-class entity.

**Comment by alygin** [comment]
It's already implemented. You can open any .out file and run the "Visualize TLC output" command. It works if the `-tool` option was used when running in TLC.

I believe, it relates to [this discussion](https://groups.google.com/forum/#!msg/tlaplus/IKeBN2xARCQ/kMomXKkfFAAJ), and the current implementation should do the job.

**Comment by alygin** [comment]
I'm closing this one, since the feature is already supported. Feel free to reopen the issue if you meant something else, or file a bug if there're problems with visualising of .out files.
