### ISSUE TITLE
"Operator override" is treated as an error

### ISSUE THREAD

**Issue by alygin** [alygin/vscode-tlaplus#124]
Extracted from #123

When TLC issues the "Loading ... operator override ..." message, the extension displays it as an error:

![tlc-message-2168](https://user-images.githubusercontent.com/2101250/69491199-c7ee5e80-0ea2-11ea-9e02-9c112ad1cd0f.png)

It should be tread as a simple informative message.

cc @lemmy

**Comment by alygin** [comment]
Reopen until tested

**Comment by alygin** [comment]
@lemmy, the fix is available in the [v1.3 pre-release](https://github.com/alygin/vscode-tlaplus/releases).

**Comment by alygin** [comment]
@lemmy, v1.3 is released with the fix, so I'm closing the issue. Please, feel free to reopen it if the problem is not solved.

**Comment by lemmy** [comment]
The release log mentions the term _overloading_ whereas in TLC jargon the term used is _module override_. I would suggest to keep the terminology aligned.  Also, overloading has usually a different meaning (same operator with different set/type of parameters).

**Comment by alygin** [comment]
@lemmy, thanks, I totally agree. Fixed.
