### ISSUE TITLE
Long records in error trace un-viewable

### ISSUE THREAD

**Issue by dricketts** [alygin/vscode-tlaplus#127]
In the error trace, if an element is a function with a domain of size 1, then it doesn't get further decomposed in the error trace display. This is a problem if that function looks like:
```
x :> [field1 |-> val1, ..., field10 |-> val10]
```
With many fields, the string representation runs off the right end of the TLC view with "...". There doesn't seem to be a horizontal scroll bar or a way to expand the element vertically.

**Comment by alygin** [comment]
Yeah, I think an additional panel should be implemented that would display the whole value with scrolling. Like in the Toolbox.

**Comment by alygin** [comment]
The extension now allows you to:
- display a variable value (properly formatted) in a new scratch file,
- copy a variable value to clipboard.

The features are accessible in the latest pre-release: https://github.com/alygin/vscode-tlaplus/releases. I'm going to publish it in the nearest future.

**Comment by alygin** [comment]
@dricketts, v1.3 is released with the described features, so I'm closing the issue. I hope it helps you deal with long variable values.
