### ISSUE TITLE
Add support to Graphviz dot output

### ISSUE THREAD

**Issue by LordGordonQ** [alygin/vscode-tlaplus#128]
TLA+ Toolbox supports the generation of Graphviz's dot files: https://stackoverflow.com/questions/52055716/tla-how-to-visualize-the-state-graph

It would be really useful to have this option enabled in this plugin, so that I can then open dot files in VS Code and visualize the graph (ie with https://marketplace.visualstudio.com/items?itemName=EFanZh.graphviz-preview)

**Comment by LordGordonQ** [comment]
https://github.com/tlaplus/tlaplus/issues/403

**Comment by lemmy** [comment]
See tlaplus/tlaplus#403 for TLC's command-line.

![Peek 2019-11-30 08-08](https://user-images.githubusercontent.com/88777/69902997-c6141780-1348-11ea-9861-50662f785310.gif)

**Comment by LordGordonQ** [comment]
@lemmy Thanks for the workaround.

A nice improvement for this plugin could be to add a specific setting so that the output file is emitted automatically with the name of the model (if I'm checking `model.tla` I would like to have `model.dot`).

**Comment by alygin** [comment]
@LordGordonQ, I've added the `specName` and `modelName` variables that you can use in the `TLC: Model Checker Options` setting. They are substituted to the .tla and .cfg file names (without extensions) respectively. For instance, `-dump out ${specName}.out` will be substituted to `-dump out model.out` in your case.

It'll be released in v1.3. The [pre-release](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.3.0-alpha.2) is already available should you decide to try it earlier.

**Comment by alygin** [comment]
@LordGordonQ, v1.3 is released with support of `specName` and `modelName` variables, so I'm closing the issue.

**Comment by LordGordonQ** [comment]
Tried with `-dump dot,actionable,colorize ${specName}.dot` and works perfectly. 

Thanks

**Comment by sheeraSearch82** [comment]
How to visualize the .dot files after it is generated using -dump dot,actionable,colorize ${specName}.dot?

**Comment by alygin** [comment]
@sheeraSearch82, you need to install one of the Graphviz-viewer extensions. I believe, these two are the most popular:

- [Graphviz Interactive Preview](https://marketplace.visualstudio.com/items?itemName=tintinweb.graphviz-interactive-preview)
- [Graphviz Preview](https://marketplace.visualstudio.com/items?itemName=EFanZh.graphviz-preview)

**Comment by sheeraSearch82** [comment]
Thanks @alygin . I installed and it worked fine. Thanks for the VScode support for TLA+. I wanted to know, will there be TLAPS also enabled as part of TLA+ in VSCode? If any such plans, is there a probable date of release?

**Comment by alygin** [comment]
@sheeraSearch82 , there's issue #153 for TLAPS support. I have no capacity to work on it at the moment, yet I'm planning to get back to it in the future. No commits about particular dates, sorry :)
