### ISSUE TITLE
Parse on save option

### ISSUE THREAD

**Issue by scott-fleischman** [alygin/vscode-tlaplus#133]
It would be useful to have an option so you can parse a `.tla` file on save, like the TLA+ toolbox does.

**Comment by alygin** [comment]
@scott-fleischman, please, have a look at this wiki page: [Automatic module parsing](https://github.com/alygin/vscode-tlaplus/wiki/Automatic-Module-Parsing). Does it do the job?

**Comment by scott-fleischman** [comment]
Yes, thanks!
