### ISSUE TITLE
Add setting for path to jar file.

### ISSUE THREAD

**Issue by scott-fleischman** [alygin/vscode-tlaplus#134]
It would be useful to allow a setting to the `tla2tools.jar` file so one can maintain consistency with other users and a build server version of tla tools.

**Comment by lemmy** [comment]
@scott-fleischman https://github.com/tlaplus/tlaplus/issues/393#issuecomment-561732695 is a related discussion.  https://github.com/tlaplus/tlaplus/issues/306 discusses TLA+ and continuous integration.

**Comment by alygin** [comment]
@lemmy, thanks for adding some context here.
There're several classpath-related features, like changing `tla2tools.jar`, adding community modules and other libraries. I think it could be implemented by some smart handling of the `-cp` option in the already existing Java Options setting.

**Comment by lemmy** [comment]
Until this gets properly addressed, what about providing a nightly build of the extension that always includes the last version of https://nightly.tlapl.us

**Comment by alygin** [comment]
The feature is provided in the latest pre-release ([how-to](https://github.com/alygin/vscode-tlaplus/issues/123#issuecomment-581012375)). Will be released soon.

**Comment by alygin** [comment]
@scott-fleischman, the feature is released in v1.4. Here's the description of how it works: https://github.com/alygin/vscode-tlaplus/wiki/Java-Options#class-path
