### ISSUE TITLE
How to disbable deadlock checking?

### ISSUE THREAD

**Issue by el10savio** [alygin/vscode-tlaplus#135]
Is there a way to disable deadlock checking in the TLA+ settings, if so what is the format?

**Comment by lemmy** [comment]
You have to pass "-deadlock" in the extension's settings:

![Screenshot from 2019-12-18 09-10-40](https://user-images.githubusercontent.com/88777/71107639-55596180-2176-11ea-837a-e34d8a758579.png)

Note that this is a global and not a per-model setting.

**Comment by el10savio** [comment]
Thanks! I'll do that. Probably you could also add to vscode-tlaplus a deadlock checkbox button to the model checker window to switch the deadlock settings.

**Comment by lemmy** [comment]
The easiest thing to me seems to add another "Check Model" command that extends the existing one with deadlock checking: "Check Model (including deadlocks)".
