### ISSUE TITLE
Cmd + Click for "Go To Definition" not working as expected

### ISSUE THREAD

**Issue by will62794** [alygin/vscode-tlaplus#138]
When editing many other languages in VS Code (e.g. Python, C++, etc.), you are able to jump to the definition of a symbol by holding Cmd or Control (⌘ on macOS) and clicking on the symbol. This doesn't seem to work properly in the TLA+ extension. The "Go To Declaration" action does work as expected, and that action (`editor.action.goToDeclaration`) can be bound to a keyboard shortcut, but I have not been able to use cmd+click to jump to a symbol definition. Perhaps this could be solved by defining the "Go To Definition" action appropriately within the TLA+ extension. Also, maybe there is a way to enable this in the VS Code settings that I have not discovered. The cmd+click behavior is a feature of the TLA+ Toolbox that is very nice to have and would be great to have in the VS code extension as well. I am running on macOS 10.13.6 with TLA+ extension version 1.3.1.

**Comment by alygin** [comment]
The "Go to Declaration" hasn't been implemented yet (it requires implementation of the [DeclarationProvider](https://code.visualstudio.com/api/references/vscode-api#DeclarationProvider) interface). Though, I already made some steps towards it by implementing the symbols provider, so one can jump to a symbol declaration with the "Go to Symbol in File..." command (Cmd + Shift + O on macOS) or from the [Outline view](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view).

I agree that this command is extremely useful. Given the fact that the extension is already collecting information about symbols definition, it shouldn't be hard to implement "Go to Declaration", at least for the symbols declared in the same file. I think it'll be added in one of the nearest releases. Cross-file jumps would require more work, I think it'll be a separate issue.

**Comment by will62794** [comment]
Ok, thanks for letting me know it's on your agenda. "Go To Declaration" for symbols within the same file would be more than adequate, in my opinion, at least for the initial implementation.

**Comment by alygin** [comment]
Available in the [latest pre-release](https://github.com/alygin/vscode-tlaplus/releases).

**Comment by alygin** [comment]
Released in v1.4.
