### ISSUE TITLE
Improve visualisation of multiple error traces

### ISSUE THREAD

**Issue by alygin** [alygin/vscode-tlaplus#146]
When using the `-continue` option, TLC may produce multiple error traces. At the moment, the extension displays all the error traces at once, one below another, which affects usability and might lead to performance issues when there're many of them.

It would be more convenient to display only one error trace and switch between them using links next to error messages.

**Comment by lemmy** [comment]
We might want to improve TLC's output markers with multiple traces because TLC currently makes it difficult to parse them.

**Comment by alygin** [comment]
Actually, it looks pretty parseable to me. The current parser already can handle such cases properly, I only need to slightly change the data structure I use for storing errors.

**Comment by alygin** [comment]
Available in the v1.4 beta.
