### ISSUE TITLE
Publish to marketplace Open VSX

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#160]
A user cannot install vscode-tlaplus into [Gitpod](https://www.gitpod.io/) from the main marketplace due to incompatibilities.  Thus, please also publish vscode-tlaplus to [Open VSX](https://open-vsx.org/).

(background: https://www.gitpod.io/blog/open-vsx-in-gitpod/)

**Comment by alygin** [comment]
Published: https://open-vsx.org/extension/alygin/vscode-tlaplus
