### ISSUE TITLE
Bug/confusing: tla2tools.jar override cannot handle quotes in path on Windows

### ISSUE THREAD

**Issue by ahelwer** [alygin/vscode-tlaplus#169]
Per [this doc](https://github.com/alygin/vscode-tlaplus/wiki/Java-Options), you can override the tla2tools.jar path by passing a -cp parameter with a path to a different jar in the java options. However, this confusingly does not handle paths in quotes, so the following does not work (the extension falls back to the included tla2tools.jar):

```
-cp "C:\tla-toolbox\nightly\2020-09-15\tla2tools.jar"
```

However, this works:

```
-cp C:\tla-toolbox\nightly\2020-09-15\tla2tools.jar
```

**Comment by alygin** [comment]
@ahelwer, [v1.5.1](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.5.1) (officially released) should fix it.
Thanks for the report!

**Comment by alygin** [comment]
Fixed in v1.5.1. Feel free to reopen the issue if the problem still remains.

**Comment by ahelwer** [comment]
@alygin I see that in the latest commit (1b9a2e59fcdf756b8c711b9815f423be4ab8056d) this test is now failing; related?

```
TLA+ Tools Test Suite
       Allows to add custom libraries to classpath via -cp:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

[
  '-cp',
  'CommunityModules.jar;Foo.jar;/default/tla2tools.jar',
  '-XX:+UseParallelGC'

should loosely deep-equal

[
  'CommunityModules.jar:Foo.jar;/default/tla2tools.jar',
  '-XX:+UseParallelGC'
]
      + expected - actual

       [
         "-cp"
      -  "CommunityModules.jar;Foo.jar;/default/tla2tools.jar"
      +  "CommunityModules.jar:Foo.jar;/default/tla2tools.jar"
         "-XX:+UseParallelGC"
       ]

        at Context.<anonymous> (c:\Users\ahelwer\source\vscode-tlaplus\out\tests\suite\tla2tools.test.js:70:16)
        at processImmediate (internal/timers.js:439:21)
```

The test expects a colon (`:`) after `CommunityModules.jar` but the code now produces a semicolon (`;`).

**Comment by alygin** [comment]
@ahelwer, it looks like the problem was there long before the latest commits. And yes, it's because the expected value has a hardcoded path delimiter. This should fix it: https://github.com/alygin/vscode-tlaplus/commit/64edbef6869d2ee1f1d9e2e251ed80d6bef7d0c7
