### ISSUE TITLE
Running keeps showing "Computing initial states"

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#173]
With 1.5.1

![Screenshot from 2020-10-20 16-54-33](https://user-images.githubusercontent.com/88777/96656625-0da2e980-12f5-11eb-9d5e-23d69478d749.png)

After a while, the label "Running" keeps showing "Checkpointing".

**Comment by alygin** [comment]
@lemmy , could you, please, provide the resulting .out file?

**Comment by lemmy** [comment]
Different run but same behavior:

[MC.zip](https://github.com/alygin/vscode-tlaplus/files/5424078/MC.zip)

**Comment by alygin** [comment]
> Different run but same behavior:

@lemmy , did it show the "Checkpointing" status during this run? I can't find the message 2195 code, which is the only trigger that switches checking status to "Checkpointing".

If you just open this MC.out in VSCode and run the "Visualize TLC output" on it, does it show the correct result?

**Comment by lemmy** [comment]
Sorry for the confusion...  IIRC `MC.zip` did *not* run long enough to take a checkpoint.  Below is a screenshot of what the webview looks like:

![Screenshot from 2020-11-02 10-58-12](https://user-images.githubusercontent.com/88777/97907611-61043700-1cfa-11eb-83d2-21c9f5929186.png)
