### ISSUE TITLE
Cardinality of largest enumerable set

### ISSUE THREAD

**Issue by RhinocerosBomb** [alygin/vscode-tlaplus#174]
Is it possible to enable TLC options like in toolbox? Specifically I want to be able to set the Cardinality of largest enumerable set.

**Comment by alygin** [comment]
Sure. You can provide any [TLC option](https://lamport.azurewebsites.net/tla/tlc-options.html) using the `TLC Model Checker : Options` setting on the settings panel ([more details](https://github.com/alygin/vscode-tlaplus/wiki/Settings)).

To do the same thing Toolbox does when you set "Cardinality of larges enumerable set", you need the `maxSetSize` option. For instance, `-maxSetSize 2000000`.

**Comment by lemmy** [comment]
Regardless of how it is done with the extension... In ~10 years working with TLA+, I've never had to increase `maxSetSize`.  Without knowing what you're doing, I'd suggest checking if you can minify/simplify your problem.

**Comment by alygin** [comment]
@RhinocerosBomb, I'm closing the issue. I hope the answers helped you with your problem.
