### ISSUE TITLE
SANY crashes are presented to user as parse success

### ISSUE THREAD

**Issue by ahelwer** [alygin/vscode-tlaplus#183]
**Version Info**

VS Code TLA+ Extension Version: 1.5.1
JRE version: AdoptOpenJDK build 15.0.1+9
OS version: Windows 10

**What happened?**

I tried to use the TLA+ VS Code extension to parse specs that caused a NullPointerException in SANY (see https://github.com/tlaplus/tlaplus/issues/553) and the TLA+ VS Code extension presented as though no parse errors occurred in the module.

**What did you expect to happen?**

I expected to be notified in some way that there was a parse failure (in this case manifesting as SANY crashing with a NullPointerException)

**Steps to reproduce**

 1. Create a file `Test.tla` filled with the malformed specs from https://github.com/tlaplus/tlaplus/issues/553
 2. Parse the specs in the TLA+ VS Code extension

**Comment by alygin** [comment]
The fix is available in the [v1.5.2-alpha.2 pre-release](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.5.2-alpha.2).

**Comment by alygin** [comment]
Fix published in v1.5.2
