### ISSUE TITLE
Java Home setting wants an URI, but it's actually supposed to be a path

### ISSUE THREAD

**Issue by kubukoz** [alygin/vscode-tlaplus#195]
Whether in the settings panel:

![image](https://user-images.githubusercontent.com/894884/105788459-da6d9780-5f80-11eb-9544-ba201370f3cb.png)

or in the file:

![image](https://user-images.githubusercontent.com/894884/105788449-d477b680-5f80-11eb-963c-10dc10bf08fe.png)

the setting wants the path to be an URI, but only works when I provide a filesystem path. Prefixing with `file://` actually causes the TLC not to run at all, and the error to appear:

![image](https://user-images.githubusercontent.com/894884/105788540-fb35ed00-5f80-11eb-9b22-0535f55b809d.png)

**Comment by alygin** [comment]
The fix is available in [v1.5.3-alpha.1](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.5.3-alpha.1)

**Comment by alygin** [comment]
@kubukoz, thanks for the report and for the fix!
