### ISSUE TITLE
[Feature] Expose TLC REPL in VSCode terminal

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#212]
Recent versions of TLC come with a (simple) REPL.  It would be great if the REPL was integrated into the VSCode terminal. 

```shell
markus@avocado:/opt/toolbox$ java -cp tla2tools.jar tlc2.REPL
Welcome to the TLA+ REPL!
TLC2 Version 2.16 of Day Month 20??
Enter a constant-level TLA+ expression.
(tla+) TRUE
TRUE
```

**Comment by alygin** [comment]
A command that calls [`vscode.window.createTerminal()`](https://code.visualstudio.com/api/references/vscode-api#window.createTerminal) should do the job.

**Comment by lemmy** [comment]
Addressed by PR https://github.com/alygin/vscode-tlaplus/pull/241 provided by @edaena
