### ISSUE TITLE
Syntax highlighting active outside of module boundaries

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#217]
```tla
Text up here shouldn't cause "shouldn" to be highlighted (the syntax grammar thinks "shouldn" is a primed variable).
----- MODULE M -----
...
=====
```

![syntax](https://user-images.githubusercontent.com/88777/119925444-545f5e80-bf2a-11eb-84fe-34308f6a768f.png)

**Comment by alygin** [comment]
This is very similar to #117. [Semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) is stable since VSCode v1.48, so it should be doable.

**Comment by ahelwer** [comment]
@lemmy the toolbox highlights keywords and comments outside of module boundaries; is this desired behavior?

**Comment by lemmy** [comment]
I don't know if this is intentional, but I like its behavior better than highlighting `don't`, `doesn't`, .... Perhaps, the pretty-printer is the authority?

**Comment by lemmy** [comment]
Marking as closed thanks to @edaena!
