### ISSUE TITLE
How do I use sets in config file?

### ISSUE THREAD

**Issue by anton-trunov** [alygin/vscode-tlaplus#219]
For instance, how do I define something like this?
```
CONSTANT
    Foo = 0..42
```

**Comment by lemmy** [comment]
You can't because TLC's config file doesn't support arbitrary expressions.  This is why the Eclipse-based Toolbox generates an `MC.cfg` *and* an `MC.tla` file.  Related #159

**Comment by Alexander-N** [comment]
See https://stackoverflow.com/questions/59101827/ for how to manually create these MC files.

**Comment by alygin** [comment]
@anton-trunov, I hope the answers helped.
