### ISSUE TITLE
Support inlined TLC configs

### ISSUE THREAD

**Issue by lemmy** [alygin/vscode-tlaplus#220]
Checking spec  `A.tla`  without  `A.cfg`  opens a dialog saying that one has to create the config file  `A.cfg`.  Instead, @klinvill new dialog should pop up first to let users enter `-config MCA.cfg`, and only afterward fail iff no alternative config is given.

**Comment by klinvill** [comment]
Right now this use case is handled through the `Check model with TLC using non-default config` which will prompt you to enter a config file before it prompts for additional options. Is that command sufficient?

As a side note, it looks like you can change the config for the normal command by putting a `-config` argument in, however the name of that config is properly reflected in the model checking pane.

**Comment by lemmy** [comment]
Obviously, it is easy to get lost in the "sea" of TLA+ commands.  Regarding `Check model with TLC using non-default config` specifically, the label doesn't make sense.  I suggest combining most if not all `Check ...` commands into one (or two).  For starters, [`Debug a running model`](https://github.com/alygin/vscode-tlaplus/issues/221#issuecomment-854292239) can probably be removed.  The command is useful when one debugs the debugger, but most users won't do that.  In special cases, users can manually pass `-debugger` in the prompt.
