### ISSUE TITLE
Better to have code formatting

### ISSUE THREAD

**Issue by wordhardqi** [alygin/vscode-tlaplus#74]

**Comment by alygin** [comment]
Actually, there was code formatting a couple of versions ago, but I removed it because it didn't work good enough. I'll surely get back to it.

**Comment by alygin** [comment]
Just update to v0.5.0, and don't forget to switch on the "Text Editor / Formatting / Format On Type" setting.

**Comment by alygin** [comment]
The on-type formatting feature was implemented, so I'm closing this issue, though I've also opened #99 about the code blocks formatting.
