### ISSUE TITLE
Change default indentation to 2 spaces

### ISSUE THREAD

**Issue by alygin** [alygin/vscode-tlaplus#87]
At the moment, the default setting for the code formatter is 4 spaces. I'd like to change it to 2 spaces for TLA+, PlusCal and .cfg-files, but not sure yet.

4 spaces:
* the default setting in the Toolbox
* the default setting in most of the text editors

2 spaces:
* used in pretty all the TLA+ examples / books / tutorials
* feels more suitable to me, since
  * TLA+ code is usually indented in accordance with `/\`'s, `\/`'s and other operators or syntax constructions, so pure tabs are rare
  * PlusCal code is usually not very convoluted, and 2 spaces indentation seems enough to easily navigate its structure
  * .cfg files are even simpler
* IDEs and text editors now provide many tools for dealing with code structure (indentation guide lines, folding, current block highlighting etc.) that doing all this with long spaces seems redundant.

Any input on the issue is welcomed.

**Comment by suhr** [comment]
Four spaces identation is more visible in the generated pdf. Also, it aligns nicely with `LET`:

```tla
ReplaceNode(table, id, new) ==
    LET bs  == table.buckets
        k   == CHOOSE k \in 0..Len(bs): id \in {n.id : n \in bs[k]}
        old == CHOOSE old \in bs[k]: old.id = id
    IN
        [table EXCEPT !.buckets[k] = (bs[k] \ {old}) \cup {new}]
```

**Comment by alygin** [comment]
One more opinion: https://github.com/alygin/vscode-tlaplus/issues/67#issuecomment-529672996

**Comment by alygin** [comment]
BTW, here's an instruction on how to change the formatting style: [Formatting Preferences](https://github.com/alygin/vscode-tlaplus/wiki/Formatting-Preferences).

**Comment by alygin** [comment]
It looks like having 4 spaces by default + documentation on how to change preferences is safe choice.
