### ISSUE TITLE
A command to generate PDF

### ISSUE THREAD

**Issue by suhr** [alygin/vscode-tlaplus#89]
TLA toolbox can generate PDF from a specification. It would be nice to able to generate PDF in VS Code too.

**Comment by alygin** [comment]
Yeah, I was thinking about including export-to-PDF in v1.0. Actually, the feature consists of two commands: generate a .tex file (might be of interest per se), and convert this .tex file to a PDF. They both are pretty easy to implement (it looks like the VS Code Tasks API should work for both of them), though the latter requires an external tool (pdflatex by default) that's not present on the user computers by default, so additional checks and documentation must be added (the same way it's done for JVM now).

BTW, VS Code provides all the necessary functionality to register your own [custom task](https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks) and easily run it (even with a keyboard shortcut). Just add a shell-task that runs `java -cp tla2tools.jar tla2tex.TLA spec.tla && pdflatex spec.pdf`. You can use this approach until the feature is added to the extension if it's an important part of your workflow.

**Comment by alygin** [comment]
Implemented in 339eb2f7aa855ab6735d4ec432e58eeed749f434 and #98

**Comment by alygin** [comment]
[v1.0.0](https://github.com/alygin/vscode-tlaplus/releases/tag/v1.0.0) with this feature has been published 🚀
